name: Deploy live to OMV

on:
  push:
    branches: [ "live" ]

jobs:
  deploy:
    runs-on: [ "docker" ]  # ggf. anpassen

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install ssh + rsync
        run: |
          if command -v apt-get >/dev/null 2>&1; then
            apt-get update
            apt-get install -y --no-install-recommends openssh-client rsync
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache openssh-client rsync
          fi

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Trust host
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Rsync to target (no perms/owner change)
        env:
          SSH_HOST:   ${{ secrets.SSH_HOST }}
          SSH_PORT:   ${{ secrets.SSH_PORT }}
          SSH_USER:   ${{ secrets.SSH_USER }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          rsync -a --delete \
            --exclude '.git' \
            -e "ssh -p ${SSH_PORT}" \
            ./ "${SSH_USER}@${SSH_HOST}:${TARGET_DIR}/"

      - name: Rebuild & restart (optional)
        env:
          SSH_HOST:   ${{ secrets.SSH_HOST }}
          SSH_PORT:   ${{ secrets.SSH_PORT }}
          SSH_USER:   ${{ secrets.SSH_USER }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          ssh -p "${SSH_PORT}" "${SSH_USER}@${SSH_HOST}" \
            "cd '${TARGET_DIR}' && \
             if [ -f docker-compose.yml ] || [ -f compose.yml ]; then \
               docker compose up -d --build || docker-compose up -d --build || true; \
             else \
               echo 'No compose file – skipping rebuild'; \
             fi"
