name: Deploy live to OMV
on:
  push:
    branches: ["live"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ["docker"]   # dein Label

    steps:

      - name: Forgejo in /etc/hosts eintragen
        run: |
          echo "${{ secrets.FORGEJO_IP }} git.cube.fritz.box" >> /etc/hosts
          getent hosts git.cube.fritz.box

      - name: CA bereitstellen (falls Runner-Env nicht greift)
        env:
          INTERNAL_CA_PEM: ${{ secrets.INTERNAL_CA_PEM }}
        run: |
          apt-get update || true
          apt-get install -y --no-install-recommends ca-certificates || true
          mkdir -p /usr/local/share/ca-certificates
          printf '%s\n' "$INTERNAL_CA_PEM" > /usr/local/share/ca-certificates/internal-ca.crt
          update-ca-certificates || true
          [ -f /etc/ssl/certs/ca-certificates.crt ] && \
            git config --global http."https://git.cube.fritz.box/".sslCAInfo /etc/ssl/certs/ca-certificates.crt
      

      - uses: actions/checkout@v4

      - name: Install rsync
        run: |
          apt-get update
          apt-get install -y --no-install-recommends rsync

      - name: Copy to mounted target (/deploy)
        run: |
          rsync -rltD --delete --omit-dir-times --no-perms \
            --exclude '.git' --exclude '.forgejo' \
            ./ /deploy/

      - name: Rebuild & restart (optional)
        run: |
          cd /deploy
          if [ -f docker-compose.yml ] || [ -f compose.yml ]; then
            # Docker-CLI im Jobcontainer nachinstallieren (einmal pro Job)
            if ! command -v docker >/dev/null 2>&1; then
              apt-get update
              apt-get install -y --no-install-recommends docker.io docker-compose-plugin
            fi
            docker compose up -d --build || docker-compose up -d --build
          else
            echo "No compose file – skipping rebuild"
          fi
