name: "Deploy live to OMV"
on:
  push:
    branches: ["live"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ["docker"]
    env:
      GIT_SSL_CAINFO: /etc/ssl/certs/omv-ca-bundle.crt
      SSL_CERT_FILE:  /etc/ssl/certs/omv-ca-bundle.crt

    steps:
      - name: "Sanity: CA bundle und Docker-Socket vorhanden?"
        run: |
          set -e
          whoami || true; id
          [ -r /etc/ssl/certs/omv-ca-bundle.crt ] || (echo "CA-Bundle fehlt!"; exit 1)
          [ -S /var/run/docker.sock ] || (echo "Docker socket fehlt!"; ls -l /var/run || true; exit 1)

      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Fetch Docker CLI (static)"
        env:
          DOCKER_VERSION: "27.2.0"
          DOCKER_CONFIG: "/tmp/.docker"
          HOME: "/tmp"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$DOCKER_CONFIG" /tmp/docker
          curl -fsSL "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" -o /tmp/docker/docker.tgz
          tar -xzf /tmp/docker/docker.tgz -C /tmp/docker
          /tmp/docker/docker/docker version

      - name: "Prepare target dir (/opt/omv-landingpage)"
        shell: bash
        run: |
          set -euo pipefail
          /tmp/docker/docker/docker run --rm -v /opt:/host alpine:3 sh -ceu '
            set -eux
            mkdir -p /host/omv-landingpage
            touch /host/omv-landingpage/.deploy_target
            chown -R 0:0 /host/omv-landingpage
            chmod -R 0775 /host/omv-landingpage
            ls -ld /host/omv-landingpage
          '

      - name: "Safe mirror repo -> /opt/omv-landingpage (backup + sync)"
        env:
          TARGET_DIR: "/opt/omv-landingpage"
        shell: bash
        run: |
          set -euo pipefail
          [ -n "${TARGET_DIR}" ] && [ "${TARGET_DIR}" = "/opt/omv-landingpage" ] || { echo "Unsafe TARGET_DIR"; exit 2; }
          # Guard vorhanden?
          /tmp/docker/docker/docker run --rm -v "${TARGET_DIR}":/dst alpine:3 sh -ceu '
            [ -f /dst/.deploy_target ] || { echo "Missing .deploy_target in ${TARGET_DIR}"; exit 3; }
          '
          # Backup des aktuellen Zustands
          TS="$(date +%Y%m%d_%H%M%S)"
          /tmp/docker/docker/docker run --rm -v "${TARGET_DIR}":/dst -v /opt:/opt-host alpine:3 sh -ceu '
            set -eux
            cd /dst
            tar -czf "/opt-host/omv-landingpage._backup_${TS}.tgz" . || true
          '
          # Sync: Dateien vom Repo ins Ziel kopieren (keine Full-Deletes)
          /tmp/docker/docker/docker run --rm -v "${GITHUB_WORKSPACE:-.}":/src:ro -v "${TARGET_DIR}":/dst alpine:3 sh -ceu '
            set -eux
            cp -a /src/. /dst/
            echo "--- /dst after copy ---"
            ls -la /dst
          '

      - name: "List host dir (/opt/omv-landingpage)"
        shell: bash
        run: |
          set -euo pipefail
          /tmp/docker/docker/docker run --rm -v /opt/omv-landingpage:/w alpine:3 sh -ceu '
            echo "--- Inhalt /w ---"; ls -la /w;
            echo "--- mögliche Compose-Dateien ---";
            for f in compose.yaml compose.yml docker-compose.yaml docker-compose.yml; do
              [ -f "/w/$f" ] && echo "gefunden: $f";
            done
            [ -f /w/Dockerfile ] && echo "Dockerfile vorhanden."
          '

      - name: "Compose down+up at host:/opt/omv-landingpage"
        env:
          DOCKER_CONFIG: "/tmp/.docker"
          HOME: "/tmp"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$DOCKER_CONFIG"
          # Down (tolerant)
          /tmp/docker/docker/docker run --rm             -v /opt/omv-landingpage:/workspace             -v /var/run/docker.sock:/var/run/docker.sock             -w /workspace             docker/compose:latest             -p omv-landingpage down --remove-orphans || true
          # Up (build)
          /tmp/docker/docker/docker run --rm             -v /opt/omv-landingpage:/workspace             -v /var/run/docker.sock:/var/run/docker.sock             -w /workspace             docker/compose:latest             -p omv-landingpage up -d --build
