name: Deploy OMV Landingpage

on:
  push:
    branches: [ live ]

jobs:
  deploy:
    runs-on: docker
    steps:
      - name: "SSH + Deploy (Host-Modus unter /opt)"
        env:
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          REPO_URL: ssh://git@git.cube.fritz.box:2222/rob/OMV-Landingpage.git
          BRANCH: live
          PROJECT_SLUG: omv-landingpage
          PROJECT_DIR: /opt/omv-landingpage   # <- frei wählbar unter /opt
        run: |
          set -euxo pipefail

          # Alpine-/Debian-Runner abholen, was wir brauchen
          if [ -f /etc/alpine-release ]; then
            apk add --no-cache openssh git ca-certificates
          elif command -v apt-get >/dev/null 2>&1; then
            apt-get update
            apt-get install -y --no-install-recommends openssh-client git ca-certificates
          fi

          # SSH vorbereiten
          install -d -m 700 /root/.ssh
          printf '%s' "$DEPLOY_SSH_PRIVATE_KEY" > /root/.ssh/forgejo_deploy
          chmod 600 /root/.ssh/forgejo_deploy
          tr -d '\r' < /root/.ssh/forgejo_deploy > /tmp/k && cat /tmp/k > /root/.ssh/forgejo_deploy && rm /tmp/k

          if [ -n "${DEPLOY_KNOWN_HOSTS:-}" ]; then
            printf '%s\n' "$DEPLOY_KNOWN_HOSTS" > /root/.ssh/known_hosts
          else
            ssh-keyscan -p 2222 -t ed25519 git.cube.fritz.box \
              | sed -E 's/^git\.cube\.fritz\.box/[git.cube.fritz.box]:2222/' \
              > /root/.ssh/known_hosts
          fi
          chmod 644 /root/.ssh/known_hosts

          export GIT_SSH_COMMAND='ssh -i /root/.ssh/forgejo_deploy -o IdentitiesOnly=yes -o UserKnownHostsFile=/root/.ssh/known_hosts -o StrictHostKeyChecking=yes'

          # Projektverzeichnis auf dem Host
          mkdir -p "$PROJECT_DIR"
          cd "$PROJECT_DIR"

          # Erst-Clone oder Update
          if [ ! -d .git ]; then
            git clone "$REPO_URL" .
          fi
          git remote set-url origin "$REPO_URL"
          git fetch --prune origin
          git reset --hard "origin/${BRANCH}"
          # optional klinisch sauber:
          # git clean -fdx

          # Docker verfügbar?
          docker -v
          docker compose version || true

          # Re-Deploy
          docker compose down || true
          docker compose up -d --build
