name: "Deploy live to OMV"
on:
  push:
    branches: ["live"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ["docker"]
    env:
      GIT_SSL_CAINFO: /etc/ssl/certs/omv-ca-bundle.crt
      SSL_CERT_FILE:  /etc/ssl/certs/omv-ca-bundle.crt

    steps:
      - name: "Sanity: CA bundle und Docker-Socket vorhanden?"
        run: |
          set -e
          whoami || true; id
          [ -r /etc/ssl/certs/omv-ca-bundle.crt ] || (echo "CA-Bundle fehlt!"; exit 1)
          [ -S /var/run/docker.sock ] || (echo "Docker socket fehlt!"; ls -l /var/run || true; exit 1)

      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Fetch Docker CLI (static)"
        env:
          DOCKER_VERSION: "27.2.0"
          DOCKER_CONFIG: "/tmp/.docker"
          HOME: "/tmp"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$DOCKER_CONFIG" /tmp/docker
          curl -fsSL "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" -o /tmp/docker/docker.tgz
          tar -xzf /tmp/docker/docker.tgz -C /tmp/docker
          /tmp/docker/docker/docker version

      - name: "Prepare target dir (/opt/omv-landingpage)"
        shell: bash
        run: |
          set -euo pipefail
          /tmp/docker/docker/docker run --rm -v /opt:/host alpine:3 sh -ceu '
            set -eux
            mkdir -p /host/omv-landingpage
            touch /host/omv-landingpage/.deploy_target
            chown -R 0:0 /host/omv-landingpage
            chmod -R 0775 /host/omv-landingpage
            ls -ld /host/omv-landingpage
          '

      - name: "Mirror repo -> /opt/omv-landingpage (tar-stream sync, no delete, no backups)"
        env:
          TARGET_DIR: "/opt/omv-landingpage"
        shell: bash
        run: |
          set -euo pipefail
          SRC="${GITHUB_WORKSPACE:-$PWD}"
          # Guard vorhanden?
          /tmp/docker/docker/docker run --rm -v "${TARGET_DIR}":/dst alpine:3 sh -ceu '
            [ -f /dst/.deploy_target ] || { echo "Missing .deploy_target in ${TARGET_DIR}"; exit 3; }
          '
          # Tar-Stream Sync: überschreibt geänderte Dateien, löscht nichts
          /tmp/docker/docker/docker run --rm             -v "${SRC}":/src:ro             -v "${TARGET_DIR}":/dst             alpine:3 sh -ceu '
              set -eux
              tar -C /src -cf - . | tar -C /dst -xf -
              echo "--- /dst after sync ---"
              ls -la /dst | head -n 200
            '

      - name: "Compose down+up at host:/opt/omv-landingpage"
        env:
          DOCKER_CONFIG: "/tmp/.docker"
          HOME: "/tmp"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$DOCKER_CONFIG"
          # Down (tolerant)
          /tmp/docker/docker/docker run --rm             -v /opt/omv-landingpage:/opt/omv-landingpage             -v /var/run/docker.sock:/var/run/docker.sock             -w /opt/omv-landingpage             docker/compose:latest             -p omv-landingpage down --remove-orphans || true
          # Up (build)
          /tmp/docker/docker/docker run --rm             -v /opt/omv-landingpage:/opt/omv-landingpage             -v /var/run/docker.sock:/var/run/docker.sock             -w /opt/omv-landingpage             docker/compose:latest             -p omv-landingpage up -d --build
