name: Deploy live to OMV
on:
  push:
    branches: ["live"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ["docker"]   # dein Label

    steps:

      - name: Forgejo in /etc/hosts eintragen
        run: |
          echo "${{ secrets.FORGEJO_IP }} git.cube.fritz.box" >> /etc/hosts
          getent hosts git.cube.fritz.box

      - name: CA bereitstellen (falls Runner-Env nicht greift)
        env:
          INTERNAL_CA_PEM: ${{ secrets.INTERNAL_CA_PEM }}
        run: |
          apt-get update || true
          apt-get install -y --no-install-recommends ca-certificates || true
          mkdir -p /usr/local/share/ca-certificates
          printf '%s\n' "$INTERNAL_CA_PEM" > /usr/local/share/ca-certificates/internal-ca.crt
          update-ca-certificates || true
          [ -f /etc/ssl/certs/ca-certificates.crt ] && \
            git config --global http."https://git.cube.fritz.box/".sslCAInfo /etc/ssl/certs/ca-certificates.crt
      

      - uses: actions/checkout@v4

      # 1) Dateien rüberkopieren (ohne Löschen) – ohne rsync
      - name: Copy repo -> /deploy (no rsync)
        shell: bash
        run: |
          set -euo pipefail
          tar -C . -cf - \
            --exclude=.git \
            --exclude=.forgejo \
            . \
          | tar -C /deploy -xpf -

      # 2) Exakte Spiegelung: nur das löschen, was im Repo NICHT (mehr) existiert
      - name: Prune files deleted in repo (no full clean)
        shell: bash
        run: |
          set -euo pipefail
          SRC="."
          DST="/deploy"

          # Optional: Dinge NIE löschen (eine pro Zeile, Relativpfade); Datei liegt im Repo-Root
          KEEPFILE=".deploy-keep"

          # Liste aller Dateien/Ordner im REPO (ohne .git/.forgejo), relative Pfade
          repo_list="$(mktemp)"
          find "$SRC" \( -path "$SRC/.git" -o -path "$SRC/.forgejo" \) -prune -o -print \
            | sed -E "s|^\./||; s|^\.$||" \
            | sed '/^$/d' \
            | sort -u > "$repo_list"

          # Liste aller Dateien/Ordner im ZIEL (relativ zu $DST)
          dst_list="$(mktemp)"
          ( cd "$DST" && find . -print | sed -E 's|^\./||; s|^\.$||' | sed '/^$/d' | sort -u ) > "$dst_list"

          # Optional: Keep-Liste abziehen
          if [ -f "$KEEPFILE" ]; then
            keep_list="$(mktemp)"
            # Kommentare/leere Zeilen filtern
            grep -vE '^\s*(#|$)' "$KEEPFILE" | sort -u > "$keep_list" || true
            # Ziel-Liste um KEPT reduzieren
            if [ -s "$keep_list" ]; then
              comm -23 "$dst_list" "$keep_list" > "${dst_list}.tmp" && mv "${dst_list}.tmp" "$dst_list"
            fi
          fi

          # Zu löschende Einträge = im Ziel, aber nicht (mehr) im Repo
          to_delete="$(mktemp)"
          comm -23 "$dst_list" "$repo_list" > "$to_delete" || true

          # Nichts zu löschen? fertig.
          [ ! -s "$to_delete" ] && exit 0

          # Erst Dateien, dann leere Verzeichnisse löschen (sicher)
          # Dateien
          awk 'length($0)>0 {print}' "$to_delete" | while IFS= read -r rel; do
            [ -z "$rel" ] && continue
            [ -e "$DST/$rel" ] || continue
            if [ -f "$DST/$rel" ] || [ -L "$DST/$rel" ]; then
              rm -f -- "$DST/$rel"
            fi
          done

          # Verzeichnisse (nur wenn leer)
          # rückwärts nach Tiefe sortieren, damit tiefe zuerst fallen
          awk 'length($0)>0 {print}' "$to_delete" \
            | awk -F/ '{print NF ":" $0}' | sort -rn | cut -d: -f2 \
            | while IFS= read -r rel; do
                [ -z "$rel" ] && continue
                [ -d "$DST/$rel" ] || continue
                rmdir --ignore-fail-on-non-empty -- "$DST/$rel" || true
              done


      - name: Rebuild & restart (optional)
        run: |
          cd /deploy
          if [ -f docker-compose.yml ] || [ -f compose.yml ]; then
            # Docker-CLI im Jobcontainer nachinstallieren (einmal pro Job)
            if ! command -v docker >/dev/null 2>&1; then
              apt-get update
              apt-get install -y --no-install-recommends docker.io docker-compose-plugin
            fi
            docker compose up -d --build || docker-compose up -d --build
          else
            echo "No compose file – skipping rebuild"
          fi
