name: Deploy OMV Landingpage

on:
  push:
    branches: [ live ]

jobs:
  deploy:
    runs-on: docker

    # Job läuft in einem Container, der die Docker-CLI bereits mitbringt.
    # KEINE additional "options:" mit -v! (verursacht die Duplicate-/Invalid-Fehler)
    container:
      image: docker:27.2.0-cli   # Alpine-basiert, docker bereits vorhanden

    steps:
      - name: Install git + ssh in job container
        run: |
          set -eux
          apk add --no-cache git openssh ca-certificates docker-cli-compose
          git --version
          ssh -V || true
          docker version
          docker compose version || true

      - name: Deploy to OMV host (/opt/omv-landingpage)
        env:
          REPO_URL: ssh://git@git.cube.fritz.box:2222/rob/OMV-Landingpage.git
          BRANCH: live
          PROJECT_DIR: /opt/omv-landingpage
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        run: |
          set -euxo pipefail

          # SSH-Material temporär für den Toolbox-Container vorbereiten
          CI_SSH_DIR="$(mktemp -d)"
          install -d -m 700 "$CI_SSH_DIR"
          printf '%s' "$DEPLOY_SSH_PRIVATE_KEY" > "$CI_SSH_DIR/forgejo_deploy"
          chmod 600 "$CI_SSH_DIR/forgejo_deploy"
          tr -d '\r' < "$CI_SSH_DIR/forgejo_deploy" > "$CI_SSH_DIR/k" && mv "$CI_SSH_DIR/k" "$CI_SSH_DIR/forgejo_deploy"
          if [ -n "${DEPLOY_KNOWN_HOSTS:-}" ]; then
            printf '%s\n' "$DEPLOY_KNOWN_HOSTS" > "$CI_SSH_DIR/known_hosts"
            chmod 644 "$CI_SSH_DIR/known_hosts"
          else
            : > "$CI_SSH_DIR/known_hosts"
          fi

          # Toolbox-Container führt den eigentlichen Deploy auf dem Host aus
          docker run --rm -u 0:0 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /opt:/opt \
            -v "$CI_SSH_DIR":/root/.ssh \
            -e REPO_URL -e BRANCH -e PROJECT_DIR \
            alpine:3.22 sh -lc '
              set -euxo pipefail
              apk add --no-cache git openssh ca-certificates docker-cli docker-cli-compose

              # known_hosts füllen (falls nicht aus Secret gekommen)
              if [ ! -s /root/.ssh/known_hosts ]; then
                ssh-keyscan -p 2222 -t ed25519 git.cube.fritz.box \
                  | sed -E "s/^git\.cube\.fritz\.box/\[git.cube.fritz.box]:2222/" \
                  > /root/.ssh/known_hosts
                chmod 644 /root/.ssh/known_hosts
              fi

              export GIT_SSH_COMMAND="ssh -i /root/.ssh/forgejo_deploy -o IdentitiesOnly=yes -o UserKnownHostsFile=/root/.ssh/known_hosts -o StrictHostKeyChecking=yes"

              # Repo direkt auf dem Hostpfad aktualisieren
              mkdir -p "$PROJECT_DIR"
              cd "$PROJECT_DIR"
              if [ ! -d .git ]; then
                git clone "$REPO_URL" .
              fi
              git remote set-url origin "$REPO_URL"
              git fetch --prune origin
              git reset --hard "origin/${BRANCH}"

              # Re-Deploy (spricht den Host-Docker über den gemounteten Socket an)
              docker compose down || true
              docker compose up -d --build
              docker compose ps
            '

          rm -rf "$CI_SSH_DIR"
