name: Inspect Deploy Key

on:
  workflow_dispatch:

jobs:
  inspect-deploy-key:
    runs-on: ubuntu-latest
    steps:
      - name: Schreibe Secret in Datei (privat)
        shell: bash
        run: |
          umask 077
          cat > deploy_key <<'EOF'
  ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
  EOF
  # zur Sicherheit: korrekte Rechte
  chmod 600 deploy_key

- name: Public Key & Fingerprint ableiten
  shell: bash
  run: |
    # Public Key aus Private Key erzeugen
    ssh-keygen -y -f deploy_key > deploy_key.pub
    
    # Fingerprint (SHA256) berechnen
    # -E sha256 ist auf aktuellen OpenSSH-Versionen verfügbar
    ssh-keygen -lf deploy_key.pub -E sha256 > deploy_key.fingerprint || ssh-keygen -lf deploy_key.pub > deploy_
