name: Inspect Deploy Key

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: [docker]   # passt zu deinem Runner-Label (--labels docker:docker)
    steps:
      - name: Stelle sicher, dass ssh-keygen verfügbar ist
        shell: bash
        run: |
          if command -v ssh-keygen >/dev/null 2>&1; then
            exit 0
          fi
          if command -v apt-get >/dev/null 2>&1; then
            apt-get update -y && apt-get install -y openssh-client
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache openssh-keygen
          elif command -v dnf >/dev/null 2>&1; then
            dnf install -y openssh-clients
          else
            echo "Kein bekannter Paketmanager gefunden" >&2
            exit 1
          fi

      - name: Schreibe Secret in Datei (privat, 0600)
        shell: bash
        run: |
          umask 077
          printf '%s\n' "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key

      - name: Leite Public Key & Fingerprint ab (safe)
        shell: bash
        run: |
          ssh-keygen -y -f deploy_key > deploy_key.pub
          # SHA256-Fingerprint (Fallback ohne -E falls nicht unterstützt)
          if ssh-keygen -lf deploy_key.pub -E sha256 >/dev/null 2>&1; then
            ssh-keygen -lf deploy_key.pub -E sha256 > deploy_key.fingerprint
          else
            ssh-keygen -lf deploy_key.pub > deploy_key.fingerprint
          fi

          echo "== FINGERPRINT =="
          cat deploy_key.fingerprint
          echo
          echo "== PUBLIC KEY =="
          cat deploy_key.pub
