name: "Deploy live to OMV (SSH Deploy-Key)"
on:
  push:
    branches: ["live"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ["docker"]
    env:
      GIT_SSL_CAINFO: /etc/ssl/certs/omv-ca-bundle.crt
      SSL_CERT_FILE:  /etc/ssl/certs/omv-ca-bundle.crt

    steps:
      - name: "Sanity: Docker-Socket vorhanden?"
        run: |
          set -e
          [ -S /var/run/docker.sock ] || (echo "Docker socket fehlt!"; exit 1)

      - name: "Fetch Docker CLI (static)"
        env:
          DOCKER_VERSION: "27.2.0"
          DOCKER_CONFIG: "/tmp/.docker"
          HOME: "/tmp"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$DOCKER_CONFIG" /tmp/docker
          curl -fsSL "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" -o /tmp/docker/docker.tgz
          tar -xzf /tmp/docker/docker.tgz -C /tmp/docker
          /tmp/docker/docker/docker version

      - name: "Git pull live (SSH Deploy-Key) -> /opt/omv-landingpage"
        env:
          REPO_SSH: "ssh://git@git.cube.fritz.box:2222/rob/OMV-Landingpage.git"            # z. B. git@git.cube.fritz.box:owner/repo.git
          SSH_PRIVKEY: "-----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD8/Au8H3q78Quv3hU4aJMNNsPnnheSPSeoXUk8ZurM2QAAAJDvPDiv7zw4
    rwAAAAtzc2gtZWQyNTUxOQAAACD8/Au8H3q78Quv3hU4aJMNNsPnnheSPSeoXUk8ZurM2Q
    AAAEDYJQ7a9teGT2rrWY8BR1dDkW3tHt4XC1WO8GWK+mTgtfz8C7wfervxC6/eFThokw02
    w+eeF5I9J6hdSTxm6szZAAAACXJvb3RAY3ViZQECAwQ=
    -----END OPENSSH PRIVATE KEY-----"
          SSH_KNOWN: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          BRANCH: "live"
        shell: bash
        run: |
          set -euo pipefail
          : "${REPO_SSH:?Secret DEPLOY_REPO_SSH fehlt (z. B. git@git.cube.fritz.box:owner/repo.git)}"
          : "${SSH_PRIVKEY:?Secret DEPLOY_SSH_PRIVATE_KEY fehlt (privater ED25519 Deploy-Key, ohne Passphrase)}"

          /tmp/docker/docker/docker run --rm --network host             -e REPO_SSH             -e SSH_PRIVKEY             -e SSH_KNOWN             -e SSH_HOST             -e BRANCH             -v /opt/omv-landingpage:/repo             -w /repo             alpine:3 sh -ceu '
              set -eux
              apk add --no-cache git openssh-client ca-certificates

              mkdir -p /root/.ssh
              chmod 700 /root/.ssh
              printf %s "$SSH_PRIVKEY" > /root/.ssh/id_ed25519
              chmod 600 /root/.ssh/id_ed25519

              GIT_SSH_OPTS="-i /root/.ssh/id_ed25519 -o IdentitiesOnly=yes"
              if [ -n "${SSH_KNOWN:-}" ]; then
                printf %s "$SSH_KNOWN" > /root/.ssh/known_hosts
                chmod 644 /root/.ssh/known_hosts
                GIT_SSH_OPTS="$GIT_SSH_OPTS -o UserKnownHostsFile=/root/.ssh/known_hosts -o StrictHostKeyChecking=yes"
              else
                if ssh-keyscan -T 3 "${SSH_HOST:-git.cube.fritz.box}" > /root/.ssh/known_hosts 2>/dev/null; then
                  chmod 644 /root/.ssh/known_hosts
                  GIT_SSH_OPTS="$GIT_SSH_OPTS -o UserKnownHostsFile=/root/.ssh/known_hosts -o StrictHostKeyChecking=yes"
                else
                  echo "WARN: ssh-keyscan fehlgeschlagen – fallback auf StrictHostKeyChecking=no"
                  GIT_SSH_OPTS="$GIT_SSH_OPTS -o StrictHostKeyChecking=no"
                fi
              fi
              export GIT_SSH_COMMAND="ssh $GIT_SSH_OPTS"

              if [ ! -d .git ]; then
                git init .
                git remote add origin "$REPO_SSH"
                git fetch --depth=1 origin "$BRANCH"
                git checkout -B "$BRANCH" FETCH_HEAD
              else
                git remote set-url origin "$REPO_SSH"
                git fetch origin "$BRANCH"
                git reset --hard "origin/$BRANCH"
              fi

              git submodule update --init --recursive || true
              git status --porcelain -b
            '

      - name: "Compose down+up (build) in /opt/omv-landingpage"
        env:
          DOCKER_CONFIG: "/tmp/.docker"
          HOME: "/tmp"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$DOCKER_CONFIG"
          /tmp/docker/docker/docker run --rm             -v /opt/omv-landingpage:/opt/omv-landingpage             -v /var/run/docker.sock:/var/run/docker.sock             -w /opt/omv-landingpage             docker/compose:latest             -p omv-landingpage down --remove-orphans || true
          /tmp/docker/docker/docker run --rm             -v /opt/omv-landingpage:/opt/omv-landingpage             -v /var/run/docker.sock:/var/run/docker.sock             -w /opt/omv-landingpage             docker/compose:latest             -p omv-landingpage up -d --build
