name: Deploy OMV Landingpage

on:
  push:
    branches: [ live ]   # ["live"] wäre auch ok

jobs:
  deploy:
    runs-on: docker

    # >>> WICHTIG: Job läuft in einem Image mit Docker-CLI
    container:
      image: docker:27.2.0-cli       # Alpine-basiert, docker CLI bereits drin
      options: >-
        --network host
        -v /var/run/docker.sock:/var/run/docker.sock
        -v /opt:/opt

    steps:
      - name: Install git + ssh in job container
        run: |
          set -eux
          apk add --no-cache git openssh ca-certificates docker-cli-compose
          git --version
          ssh -V || true
          docker version
          docker compose version || true

      - name: Deploy to OMV host (/opt/omv-landingpage)
        env:
          REPO_URL: ssh://git@git.cube.fritz.box:2222/rob/OMV-Landingpage.git
          BRANCH: live
          PROJECT_DIR: /opt/omv-landingpage
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        run: |
          set -euxo pipefail

          # --- SSH vorbereiten (im Job-Container laufen wir als root)
          install -d -m 700 /root/.ssh
          printf '%s' "$DEPLOY_SSH_PRIVATE_KEY" > /root/.ssh/forgejo_deploy
          chmod 600 /root/.ssh/forgejo_deploy
          # CRLF-Schutz
          tr -d '\r' < /root/.ssh/forgejo_deploy > /tmp/k && mv /tmp/k /root/.ssh/forgejo_deploy

          # known_hosts: Secret bevorzugt; sonst sicher via ssh-keyscan (Port 2222)
          if [ -n "${DEPLOY_KNOWN_HOSTS:-}" ]; then
            printf '%s\n' "$DEPLOY_KNOWN_HOSTS" > /root/.ssh/known_hosts
          else
            ssh-keyscan -p 2222 -t ed25519 git.cube.fritz.box \
              | sed -E 's/^git\.cube\.fritz\.box/[git.cube.fritz.box]:2222/' \
              > /root/.ssh/known_hosts
          fi
          chmod 644 /root/.ssh/known_hosts

          export GIT_SSH_COMMAND='ssh -i /root/.ssh/forgejo_deploy -o IdentitiesOnly=yes -o UserKnownHostsFile=/root/.ssh/known_hosts -o StrictHostKeyChecking=yes'

          # --- Repo im Host-Zielpfad aktualisieren (wir sehen /opt dank Mount)
          mkdir -p "$PROJECT_DIR"
          cd "$PROJECT_DIR"

          if [ ! -d .git ]; then
            git clone "$REPO_URL" .
          fi
          git remote set-url origin "$REPO_URL"
          git fetch --prune origin
          git reset --hard "origin/${BRANCH}"
          # optional:
          # git clean -fdx

          # --- Re-Deploy (Docker Compose spricht den Host-Daemon über /var/run/docker.sock an)
          docker compose down || true
          docker compose up -d --build
          docker compose ps
