name: Deploy live to OMV

on:
  push:
    branches: [ "live" ]

jobs:
  deploy:
    runs-on: [ "docker" ]

    steps:
      - name: Forgejo Host eintragen
        run: |
          echo "192.168.1.2 git.cube.fritz.box" >> /etc/hosts
          getent hosts git.cube.fritz.box

      - name: CA installieren
        env:
          INTERNAL_CA_PEM: ${{ secrets.INTERNAL_CA_PEM }}
        run: |
          set -e
          if command -v apt-get >/dev/null 2>&1; then
            apt-get update
            apt-get install -y --no-install-recommends ca-certificates
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache ca-certificates
          fi
          mkdir -p /usr/local/share/ca-certificates
          printf '%s\n' "$INTERNAL_CA_PEM" > /usr/local/share/ca-certificates/internal-ca.crt
          update-ca-certificates || true

          # git explizit auf das System-Bundle zeigen (hilft in manchen Minimal-Images)
          if [ -f /etc/ssl/certs/ca-certificates.crt ]; then
            git config --global http."https://git.cube.fritz.box/".sslCAInfo /etc/ssl/certs/ca-certificates.crt
          fi

      - name: Check out
        uses: actions/checkout@v4

      - name: Install ssh + rsync
        run: |
          if command -v apt-get >/dev/null 2>&1; then
            apt-get update
            apt-get install -y --no-install-recommends openssh-client rsync
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache openssh-client rsync
          fi

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Trust host
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Rsync to target (no perms/owner change)
        env:
          SSH_HOST:   ${{ secrets.SSH_HOST }}
          SSH_PORT:   ${{ secrets.SSH_PORT }}
          SSH_USER:   ${{ secrets.SSH_USER }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          rsync -a --delete \
            --exclude '.git' \
            -e "ssh -p ${SSH_PORT}" \
            ./ "${SSH_USER}@${SSH_HOST}:${TARGET_DIR}/"

      - name: Rebuild & restart (optional)
        env:
          SSH_HOST:   ${{ secrets.SSH_HOST }}
          SSH_PORT:   ${{ secrets.SSH_PORT }}
          SSH_USER:   ${{ secrets.SSH_USER }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          ssh -p "${SSH_PORT}" "${SSH_USER}@${SSH_HOST}" \
            "cd '${TARGET_DIR}' && \
             if [ -f docker-compose.yml ] || [ -f compose.yml ]; then \
               docker compose up -d --build || docker-compose up -d --build || true; \
             else \
               echo 'No compose file – skipping rebuild'; \
             fi"
